# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates

version: 2
updates:
  - directory: /
    labels:
      - dependencies
      - github_actions
    open-pull-requests-limit: 5
    package-ecosystem: github-actions
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - directory: /
    open-pull-requests-limit: 5
    package-ecosystem: npm
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
  - directory: /
    ignore:
      - dependency-name: boto3
      - dependency-name: botocore
    labels:
      - dependencies
      - poetry
      - python
    open-pull-requests-limit: 5
    package-ecosystem: pip
    schedule:
      interval: daily
      time: "08:00"
      timezone: America/New_York
